[package]
name = "kvs"
version = "0.1.0"
edition = "2021"
authors = ["Rafael Garcia <rafbgarcia@gmail.com>"]

[dependencies]
clap = { version = "4.5.32", features = ["derive"] }

[dev-dependencies]
assert_cmd = "2.0.16"
predicates = "3.1.3"
